Feature/errors
indigotech/onboard-beatriz-varejao pull request #12
Opened 2023-01-19 20:47 UTC by biavarejao

2023-01-19 21:05 UTC, matheusflds commented on src/resolver.ts
> +      const bool = await emailAlreadyUsed(data.email);
talvez um nome um pouquinho mais claro (hasRegisteredUser)? só `bool` pode ficar meio vago, ainda mais que vc pode ter mais validações ainda no projeto.
https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig

2023-01-19 21:05 UTC, matheusflds commented on src/resolver.ts
> +  return def;
nesses cenários você já poderia retornar direto a validação, e lembrar de utilizar !== e === ao invés de != e == (na versão "simples" o js faz umas conversões que podem levar a resultados estranhos)
```suggestion
  return user !== null;
```

2023-01-19 21:05 UTC, matheusflds commented on src/resolver.ts
> +  return def;
considerar os nomes das variáveis em inglês para padronizar (e tipar tb)

2023-01-20 11:38 UTC, alanraso requested changes

2023-01-20 11:38 UTC, alanraso commented on src/resolver.ts
> +      user.hash = Md5.hashStr(data.password);
md5 não é um bom algoritmo pra hasear senha, porque ele é relativamente fácil de quebrar. Vc poderia usar o scrypt que o node já tem internamente: https://nodejs.org/docs/latest-v18.x/api/crypto.html#cryptoscryptpassword-salt-keylen-options-callback

2023-01-20 11:38 UTC, alanraso commented on src/resolver.ts
> +      if (!thereIsLetter(data.password)) {
```suggestion
      if (!isThereALetter(data.password)) {
```

Funções e constantes booleanas no geral geralmente é legal nomear como se fosse uma pergunta. Assim fica mais claro né?

2023-01-20 11:38 UTC, alanraso commented on src/resolver.ts
> +      if (thereIsNumber(data.password)) {
```suggestion
      if (!isThereANumber(data.password)) {
```

Precisava negar aqui tbm pra jogar erro né? Pq se tiver um número ele não deveria entrar no if, certo?

2023-01-20 11:38 UTC, alanraso commented on src/resolver.ts
> +}
Aqui acabou não entrando letras maiúsculas. Uma recomendação que eu faria seria vc pesquisar uma regex que faça isso na internet. Alguém no Stack Overflow deve ter perguntado já como fazer uma regex que checa se tem uma letra em um texto no Javascript, por exemplo 🤣

2023-01-20 11:38 UTC, alanraso commented on src/resolver.ts
> +      const hasEmail = await emailAlreadyUsed(data.email);
```suggestion
      const hasEmail = await isEmailAlreadyUsed(data.email);
```

2023-01-20 11:38 UTC, alanraso commented on src/resolver.ts
> +  return user != null;
```suggestion
  return !user;
```

No geral é legal evitar comparações usando `==` ou `!=`, pq no Javascript essa comparação leva em conta apenas a falsidade ou não dos valores, não leva em conta do tipo. O ideal é sempre tentar usar `!==` e `===`. Mais detalhes [aqui](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness).

2023-01-20 11:38 UTC, alanraso commented on src/schema.ts
> +    hash: String!
Esse campo não pode estar declarado no schema, porque não é do nosso intresse retorná-lo, né?

2023-01-20 19:42 UTC, merged

2023-01-23 11:59 UTC, alanraso commented on package.json
> +    "ts-md5": "^1.3.1",
Pode remover a lib agora que não tá mais usando.

2023-01-23 11:59 UTC, alanraso commented on src/entity/User.ts
> +  hash: string;
Acho que password é melhor que `hash` porque fica mais claro qual dado está sendo guardado nessa coluna. Se vc fizesse questão de informar que fosse hasheado, poderia chamar `hashedPassword`, mas acho que essa informação não é muito necessária porque passwords sempre são hasheados de qualquer forma.

2023-01-23 11:59 UTC, alanraso commented on src/resolver.ts
> +      const { scrypt } = await import('node:crypto');
Poderia importar no começo mesmo:

```ts
import { scrypt } from 'crypto';
```

2023-01-23 11:59 UTC, alanraso commented on src/resolver.ts
>        user.email = data.email;
Aqui tem algo arriscado que é usar o callback e seguir com a opração na linha 32. Se o script de hash demorar mais do que o restante da operação, esse callback acaba sendo executado depois da chamada já ter sido retornada para o client. Aqui, dado que vc já está usando a sintaxe async/await no createUser, eu recomendaria vc transofrmar a operação de hash em Promise. Algo comum que fazemos quando alguma função externa só tem callback.

Alguns exemplos [nesse link](https://zellwk.com/blog/converting-callbacks-to-promises/).

2023-01-23 11:59 UTC, alanraso commented on src/resolver.ts
> +        if (err) throw new CustomError('Erro Interno', 401, 'erro no algoritmo hash');
Esse erro aqui, que vc até colocou na mensagem como erro interno, teria o código 500 como mais correto, né?

2023-01-23 11:59 UTC, alanraso commented on src/resolver.ts
> +}
Agora que eu percebi aqui pela função que apesar de ela chamar `isThereANumber`, na verdade ela está checando se **não tem um número**, né? Pq se tiver número ela retornaria `false`.

Talvez seja melhor vc negar o resultado aqui antes de retornar pra ficar condizente com o nome, e também negar lá no if. Pq o id deveria ser (pensando na leitura): `if (!isThereANumber(password))`.

2023-01-23 11:59 UTC, alanraso commented on src/resolver.ts
> +}
2 coisas sobre o array do alfabeto:

- A gente costuma contra-indicar siglas ou abreviações nos nomes das variáveis, para que prezemos sempre pelo código mais claro possível. O Clean Code fala um pouco disso tbm. Trocaria também o nome `str` por `text` ou algo do tipo.
- Esse array poderia ser definido apenas uma vezm fora da função. Como variável local da função `isThereALetter`, ele acaba sendo re-definido a cada execução, certo?

2023-01-23 11:59 UTC, alanraso commented on src/resolver.ts
> +  return def;
No Javascript os arrays tem várias funções nativas que ajudam a iterar e fazer alguma lógica sobre algum array. Claro que é possível fazer tudo com `forEach`, mas quando existe outro método que deixa o código mais limpo, é legal tentar utilizá-lo. Aqui, por exemplo, o [some](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) deve fazer o que vc quer:

```ts
  return alphabet.some((letter) => text.toLowerCase().includes(letter));
```

Mais exemplos: https://www.freecodecamp.org/news/the-javascript-array-handbook/